spring:
  datasource:
    url: jdbc:mysql://localhost:3306/adress?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: password
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations:
    - classpath:static/
    - file:external/